### PR TITLE
Help needed: GET from backend

### PR DESCRIPTION
**Pull request by Baschdl**
I'm struggling with the passing of values in react:
`console.log(responseJson);` yields `{world: "Hello world"}` as output, 
`console.log(responseJson.world);` yields `Hello world`, 
`result = responseJson.world;` with `return result;` and `console.log(this.getFromBackend(''));` in `sendFeedback()` yields ``. Can someone help me with that?

### CODE REVIEW

**Comment by feeds** [comment]
I tried to reproduce the error, but I got stuck getting a response at all, since I tried it with the backend running on port 8000 locally and js running on 3000, so chrome would prevent [Cross Side Scripting](https://de.wikipedia.org/wiki/Cross-Site-Scripting) and I got an error
How did you solve this?

Anyway, this is is just a guess: maybe you need to use `result = responseJson['world']` ?

**Comment by feeds** [comment]
Okay, so the `result = responseJson.world;` works like a charm, you can see that is you put the `console.log(responseJson.world);` right in the line below.

Your problem is the async fetch all. This is invoked and then in the next line an empty result is returned. You may not directly pass back result from the function, you should rather pass a callback function that takes this as a parameter into `getFromBackend(callback)` and is invoked once the data is loaded from localhost.

**Comment by feeds** [comment]
With reagards to cross side scripting: I foud the correct header and will make a pull request on this

**Comment by Baschdl** [comment]
We need our expert @juliusrueckin for discussing if we should use React's `Promise` or AJAX calls. I'm a bit in favour for Promises.

**Comment by Baschdl** [comment]
I added the corresponding backend code in the commit KDD-OpenSource/32de-python@dcac4d281c29657e9eb5abfbdb93a7a9da0434f8. It's on the branch `connection-backend-UI`.

**Comment by juliusrueckin** [comment]
To the question, whether we should use AJAX via "fecth" or promises: I think, that does not make a huge difference, both techniques are fine and fairly easy to implement. But as @Baschdl , I like Promises most.

**Comment by juliusrueckin** [comment]
To the issues with the communication between the React App on port 3000 and the python backend (!?) on prot 8000: Does your AJAX Call implementation via "fetch" work now? If not, a common issue is CORS. You have to allow the react app as a request origin with needed endpoints at your python backend server.

**Comment by Baschdl** [comment]
I set the header correctly on the mentioned branch. Now we just have the problem how we get the value out of the resolved promise.

**Comment by Baschdl** [comment]
So we had the idea that we can call a function in the `then` (callback function) and then don't have to use some wait until we have the value of the Promise. For this we have to entangle the methods and check if there are no dependencies between `render`, `sendFeedback` and the temporary `get/postToBackend`.

**Comment by feeds** [comment]
This was closed becase the changes have already been integrated in ui-path-saving

**Comment by Baschdl** [comment]
@feeds cherry picked commit 4dd9426 to other branch

**Pull request closed without merging**
